INFO 2023-08-26 21:41:41,371 autoreload 677 Watching for file changes with StatReloader
INFO 2023-08-26 21:46:03,627 autoreload 677 Watching for file changes with StatReloader
INFO 2023-08-26 21:51:08,069 autoreload 677 Watching for file changes with StatReloader
INFO 2023-08-26 21:52:53,274 autoreload 677 Watching for file changes with StatReloader
INFO 2023-08-26 21:57:38,671 autoreload 677 Watching for file changes with StatReloader
INFO 2023-08-27 15:23:50,715 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:36:21,060 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:52:07,706 autoreload 266 F:\Book_Store\bookstore\apps\trade\views.py changed, reloading.
INFO 2023-08-27 15:52:08,425 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:52:26,360 autoreload 266 F:\Book_Store\bookstore\apps\trade\views.py changed, reloading.
INFO 2023-08-27 15:52:27,160 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:52:46,157 autoreload 266 F:\Book_Store\bookstore\apps\trade\views.py changed, reloading.
INFO 2023-08-27 15:52:47,135 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:55:34,682 autoreload 266 F:\Book_Store\bookstore\apps\trade\views.py changed, reloading.
INFO 2023-08-27 15:55:35,463 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 15:58:54,529 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 16:01:33,883 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 16:03:12,699 autoreload 668 Watching for file changes with StatReloader
ERROR 2023-08-27 16:03:16,787 log 241 Internal Server Error: /
Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 35, in __getitem__
    return self._storages[alias]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 52, in create_storage
    storage_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aliyun_oss2_storage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\renderers.py", line 724, in render
    ret = template.render(context, request=renderer_context['request'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\contrib\staticfiles\storage.py", line 537, in _setup
    self._wrapped = storages[STATICFILES_STORAGE_ALIAS]
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 43, in __getitem__
    storage = self.create_storage(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 54, in create_storage
    raise InvalidStorageError(f"Could not find backend {backend!r}: {e}") from e
django.core.files.storage.handler.InvalidStorageError: Could not find backend 'aliyun_oss2_storage.backends.AliyunStaticStorage': No module named 'aliyun_oss2_storage'
ERROR 2023-08-27 16:03:16,793 basehttp 212 "GET / HTTP/1.1" 500 343293
WARNING 2023-08-27 16:03:17,063 log 241 Not Found: /favicon.ico
WARNING 2023-08-27 16:03:17,064 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 11640
INFO 2023-08-27 16:09:34,874 autoreload 668 Watching for file changes with StatReloader
ERROR 2023-08-27 16:09:37,450 log 241 Internal Server Error: /
Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 35, in __getitem__
    return self._storages[alias]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 52, in create_storage
    storage_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aliyun_oss2_storage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\renderers.py", line 724, in render
    ret = template.render(context, request=renderer_context['request'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
          ^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\contrib\staticfiles\storage.py", line 537, in _setup
    self._wrapped = storages[STATICFILES_STORAGE_ALIAS]
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 43, in __getitem__
    storage = self.create_storage(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\files\storage\handler.py", line 54, in create_storage
    raise InvalidStorageError(f"Could not find backend {backend!r}: {e}") from e
django.core.files.storage.handler.InvalidStorageError: Could not find backend 'aliyun_oss2_storage.backends.AliyunStaticStorage': No module named 'aliyun_oss2_storage'
ERROR 2023-08-27 16:09:37,456 basehttp 212 "GET / HTTP/1.1" 500 343293
INFO 2023-08-27 16:23:13,652 autoreload 266 F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\alipay\exceptions.py changed, reloading.
INFO 2023-08-27 16:23:14,433 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 16:23:36,886 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 16:23:39,712 basehttp 212 "GET / HTTP/1.1" 200 5916
INFO 2023-08-27 16:43:01,906 basehttp 212 "GET / HTTP/1.1" 200 5916
WARNING 2023-08-27 16:43:02,908 log 241 Not Found: /favicon.ico
WARNING 2023-08-27 16:43:02,909 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 11640
INFO 2023-08-27 16:43:28,860 basehttp 212 "GET /categories/ HTTP/1.1" 200 5837
INFO 2023-08-27 16:43:35,133 basehttp 212 "GET /categories/?format=api HTTP/1.1" 200 5892
INFO 2023-08-27 16:43:38,074 basehttp 212 "GET /categories/?format=json HTTP/1.1" 200 2
ERROR 2023-08-27 16:43:44,389 log 241 Internal Server Error: /userfavs/
Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "F:\Book_Store\bookstore\apps\users\views.py", line 160, in get_queryset
    return UserFav.objects.filter(user=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda3\envs\conda_bookstore\Lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001F677D1CED0>.
ERROR 2023-08-27 16:43:44,397 basehttp 212 "GET /userfavs/ HTTP/1.1" 500 166146
INFO 2023-08-27 17:20:49,044 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 17:21:32,821 basehttp 212 "GET / HTTP/1.1" 200 5916
INFO 2023-08-27 17:21:45,689 basehttp 212 "GET /swagger HTTP/1.1" 301 0
INFO 2023-08-27 17:21:45,695 basehttp 212 "GET /swagger/ HTTP/1.1" 200 2604
WARNING 2023-08-27 17:21:50,219 log 241 Not Found: /accounts/login/
WARNING 2023-08-27 17:21:50,220 basehttp 212 "GET /accounts/login/?next=/swagger/ HTTP/1.1" 404 11801
INFO 2023-08-27 17:22:20,712 basehttp 212 "GET /swagger/ HTTP/1.1" 200 2604
INFO 2023-08-27 17:22:26,375 basehttp 212 "GET /swagger/ HTTP/1.1" 200 2604
INFO 2023-08-27 17:26:26,313 autoreload 266 F:\Book_Store\bookstore\bookstore\settings.py changed, reloading.
INFO 2023-08-27 17:26:27,167 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 17:27:41,810 autoreload 266 F:\Book_Store\bookstore\bookstore\settings.py changed, reloading.
INFO 2023-08-27 17:27:42,671 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-27 17:27:45,946 basehttp 212 "GET / HTTP/1.1" 200 5916
INFO 2023-08-27 17:27:52,442 basehttp 212 "GET /swagger/ HTTP/1.1" 200 2604
INFO 2023-08-28 16:11:12,685 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-28 16:11:18,433 basehttp 212 "GET / HTTP/1.1" 200 5916
WARNING 2023-08-28 16:11:18,736 log 241 Not Found: /favicon.ico
WARNING 2023-08-28 16:11:18,738 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 11774
